---
- name: Register facts for the futher steps
  set_fact:
    smarty_compose_filename: "{{ project_dir }}/docker-compose.yml"

- name: Create certbot volume
  file:
    path: "{{ certbot.cert_path }}"
    state: directory
  run_once: true

- name: Create docker-compose directory
  file:
    path: "{{ smarty_compose_filename | dirname }}"
    state: directory
  run_once: true

- name: Deploy docker-compose configuration
  template:
    src: docker-compose.yml.j2
    dest: "{{ smarty_compose_filename }}"
  run_once: true

- name: Deploy stack from a compose file
  community.docker.docker_compose:
    project_src: "{{ smarty_compose_filename | dirname}}"
    state: present
    pull: yes

- name: Prune unused docker objects
  docker_prune:
    containers: yes
    containers_filters:
      until: 24h
    images: yes
    images_filters:
      dangling: true
    volumes: yes
    builder_cache: yes